// src/components/organisms/levels/list/LevelListItem.svelte
<script lang="ts">
  import DifficultyIcon from '@atoms/asset/DifficultyIcon.svelte';
  import Icon from '@atoms/asset/Icon.svelte';
  import Translation from '@/components/utils/Translation.svelte';
  import type { Level } from '@/types';
  import LevelListItemTagList from '@organisms/levels/list/LevelListItemTagList.svelte';

  export let level: Level;
</script>

<a class="level-list-item" href="/levels/{level.id}">
  <div class="info-container">
    <div class="basic-info">
      <div class="difficulty">
        <DifficultyIcon size={42} difficulty={level.difficulty} />

        <div class="id">ID {level.id}</div>
      </div>

      <div class="title-and-authors">
        <div class="title">
          {level.title}
        </div>

        <div class="authors">
          <div class="labels">
            <div><Translation key="LEVEL_DETAIL_MUSIC_BY" /></div>
            <div><Translation key="LEVEL_DETAIL_LEVEL_BY" /></div>
          </div>

          <div class="values">
            <div class="value-wrapper">
              <div class="value">
                {level.music.artists.map((x) => x.name).join(' & ')}
              </div>
            </div>

            <div class="value-wrapper">
              <div class="value">
                {level.creators.map((x) => x.name).join(' & ')}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    {#if import.meta.env.VITE_USE_ACCOUNT || level.tags.length}
      <div class="additional-info">
        <LevelListItemTagList {level} />

        {#if import.meta.env.VITE_USE_ACCOUNT}
          <div class="hearts">
            {#if level.tags.length}
              <div class="divider" />
            {/if}

            <div class="content">
              <Icon icon="heartOutlined" size={20} alt="Heart Icon" />
              1.4K
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </div>

  <div class="download">
    <a href={level.download} rel="noreferrer" target="_blank">
      <Icon icon="downloadFile" size={48} alt="Download Icon" />
    </a>
  </div>
</a>

<style lang="scss">
  .level-list-item {
    position: relative;
    display: flex;
    gap: 16px;
    padding: 18px 16px;
    border-bottom: 1px solid rgba(255, 255, 255, 0.2);
    white-space: nowrap;
    transition: background-color 0.2s ease-in-out;

    &:hover,
    &:focus {
      background-color: rgba(var(--color-darkblue), 0.2);
    }

    .info-container {
      display: flex;
      flex-grow: 1;
      flex-direction: column;
      justify-content: center;
      width: 0;

      @media (min-width: 1024px) {
        flex-direction: row;
        align-items: center;
        justify-content: flex-start;
      }
    }

    .basic-info {
      display: flex;
      flex-grow: 1;
      gap: 8px;
      align-items: center;
      width: 100%;

      .difficulty {
        display: flex;
        flex-direction: column;
        gap: 2px;
        align-items: center;
        width: 60px;

        .id {
          font-size: 14px;
          opacity: 0.8;
        }
      }

      .title-and-authors {
        display: flex;
        flex-grow: 1;
        flex-direction: column;
        justify-content: space-between;
        width: 0;

        .title {
          overflow-x: clip;
          height: 28px;
          font-weight: 500;
          font-size: 24px;
          line-height: 28px;
          text-overflow: ellipsis;
        }

        .authors {
          display: flex;
          flex-grow: 1;
          gap: 8px;
          align-items: center;
          height: 46px;
          line-height: 16px;

          .labels {
            display: flex;
            flex-direction: column;
            gap: 4px;
            font-weight: 300;
            opacity: 0.6;
          }

          .values {
            display: flex;
            flex-grow: 1;
            flex-direction: column;
            gap: 4px;
            width: 0;
            opacity: 0.8;

            .value-wrapper {
              position: relative;
              height: 16px;

              .value {
                position: absolute;
                overflow-x: hidden;
                width: 100%;
                height: 24px;
                text-overflow: ellipsis;
              }
            }
          }
        }
      }
    }

    .additional-info {
      display: flex;
      align-self: flex-end;
      justify-content: start;
      width: 100%;
      margin-top: 8px;

      .hearts {
        display: flex;
        gap: 12px;
        margin-left: 12px;

        .divider {
          width: 2px;
          height: 100%;
          border-radius: 100em;
          background-color: rgba(232, 232, 232, 0.4);
        }

        .content {
          display: flex;
          gap: 6px;
          align-items: center;
          font-weight: 500;
          font-size: 16px;
        }
      }

      @media (min-width: 1024px) {
        justify-content: flex-end;
        margin-top: 0;
        padding: 11px 0;
      }
    }

    .download {
      position: relative;
      align-self: center;
      width: 48px;
      opacity: 1;

      a {
        position: absolute;
        top: 0;
        right: 0;
        transform: translateY(-50%);
      }
    }
  }
</style>

// components/Level/LevelListItem.tsx
import React from 'react';
import styled from 'styled-components';
import { useTranslation } from 'react-i18next';
import { Level } from '../../typings';
import Image from 'next/image';
import millify from 'millify';
import EmptyIcon from '@assets/tagIcons/empty.svg';
import NextLink from 'next/link';

type DetailAlign = 'left' | 'center';

const DetailsContainer = styled.div`
  width: 100%;
  height: 100%;
  margin-left: 12px;
  display: flex;
  transition: opacity 0.2s ease;
  opacity: 1;
`;

const DetailsContainerHovered = styled(DetailsContainer)`
  padding-top: 12px;
  padding-bottom: 12px;
  position: absolute;
  top: 0;
  opacity: 0;
`;

const DetailItemContainer = styled.div<{ align?: DetailAlign }>`
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 40px;
  text-align: ${({ align = 'left' }) => align};
`;

const DetailItemLabel = styled.div`
  font-size: 16px;
  font-weight: 300;
  opacity: 0.6;
  overflow: hidden;
  margin-bottom: -5px;
  padding-bottom: 5px;
`;

const DetailItemValue = styled.div`
  font-size: 20px;
  font-weight: 500;
  width: 100%;
  white-space: nowrap;
  text-overflow: ellipsis;
  margin-bottom: -10px;
  padding-bottom: 10px;
  overflow: hidden;
`;

const Container = styled.a`
  height: 72px;
  position: relative;
  display: flex;
  align-items: center;
  padding: 12px 16px;
  border-radius: 12px;
  transition: background-color 0.2s ease;
  text-decoration: none !important;

  &:hover,
  &:focus {
    background: rgba(0, 0, 0, 0.2);
    ${DetailsContainer} {
      opacity: 0;
    }
    ${DetailsContainerHovered} {
      opacity: 1;
    }
  }
`;

const LevelListItemDetail: React.FC<
  React.HTMLAttributes<any> & {
    label: React.ReactNode;
    value: React.ReactNode;
    align?: DetailAlign;
  }
> = ({ label, align, value, ...props }) => {
  return (
    <DetailItemContainer align={align} {...props}>
      <DetailItemLabel>{label}</DetailItemLabel>
      <DetailItemValue>{value}</DetailItemValue>
    </DetailItemContainer>
  );
};

const LevelListItem: React.FC<{ level: Level }> = ({ level }) => {
  const { t } = useTranslation('level');

  return (
    <NextLink href='/levels/[id]' as={`/levels/${level.id}`} passHref>
      <Container>
        <Image
          width={42}
          height={42}
          alt=''
          src={require(`@assets/difficultyIcons/${level.difficulty}.svg`)}
        />
        <div style={{ flexGrow: 1, height: '100%', width: 0 }}>
          <DetailsContainer>
            <LevelListItemDetail
              style={{
                width: '36%',
                paddingRight: 12
              }}
              label={t('level')}
              value={level.title}
            />
            <LevelListItemDetail
              style={{
                width: '26%',
                paddingLeft: 12,
                paddingRight: 24
              }}
              label={t('creator')}
              value={level.creators.join(' & ')}
            />
            <LevelListItemDetail
              align='center'
              style={{
                width: '16%',
                paddingLeft: 24,
                paddingRight: 12
              }}
              label={t('bpm')}
              value={
                level.minBpm === level.maxBpm
                  ? level.minBpm
                  : `${level.minBpm} - ${level.maxBpm}`
              }
            />
            <LevelListItemDetail
              style={{
                width: '11%',
                paddingLeft: 12,
                paddingRight: 12
              }}
              label={t('tiles')}
              align='center'
              value={level.tiles}
            />
            <LevelListItemDetail
              style={{
                width: '11%'
              }}
              align='center'
              label={t('hearts')}
              value={millify(level.likes)}
            />
          </DetailsContainer>

          <DetailsContainerHovered>
            <LevelListItemDetail
              style={{
                width: 'calc(36% - 28px)',
                paddingRight: 12
              }}
              label={t('song')}
              value={level.song}
            />
            <LevelListItemDetail
              style={{
                width: 'calc(26% + 28px)',
                paddingLeft: 12
              }}
              label={t('artist')}
              value={level.artists.join(' & ')}
            />
            <LevelListItemDetail
              style={{
                paddingLeft: 24
              }}
              label={t('tags')}
              value={
                <div style={{ display: 'flex', gap: 5, marginTop: 2 }}>
                  {!level.tags.length && (
                    <span>
                      <Image src={EmptyIcon} alt='' width={25} height={25} />
                    </span>
                  )}
                  {level.tags.map((x, i) => {
                    let icon;
                    try {
                      icon = require(`@assets/tagIcons/${x.id}.svg`).default;
                    } catch (e: any) {
                      icon = null;
                    }
                    if (!icon) return null;
                    return (
                      <span key={i}>
                        <Image src={icon} alt='' width={25} height={25} />
                      </span>
                    );
                  })}
                </div>
              }
            />
          </DetailsContainerHovered>
        </div>
      </Container>
    </NextLink>
  );
};

export default LevelListItem;
